const PICK_DATE = 'PICK_DATE';
const FETCH_TIME_SLOTS = 'FETCH_TIME_SLOTS';
const SET_LOADING = 'SET_LOADING';
const SET_ERROR = 'SET_ERROR';
const SET_SELECTED_TIME_SLOT = 'SET_SELECTED_TIME_SLOT';
const SET_APPOINTMENT_NOTE = 'SET_APPOINTMENT_NOTE';
const SHOW_ALERT = 'SHOW_ALERT';
const ADD_APPOINTMENT = 'ADD_APPOINTMENT';
export {
  PICK_DATE,
  FETCH_TIME_SLOTS,
  SET_LOADING,
  SET_ERROR,
  SET_SELECTED_TIME_SLOT,
  SET_APPOINTMENT_NOTE,
  SHOW_ALERT,
  ADD_APPOINTMENT,
};
export * as ActionTypes from './ActionTypes';
