const PICK_DATE = "PICK_DATE";
const FETCH_TIME_SLOTS = "FETCH_TIME_SLOTS";
const SET_LOADING = "SET_LOADING";
const SET_ERROR = "SET_ERROR";

export { PICK_DATE, FETCH_TIME_SLOTS, SET_LOADING, SET_ERROR };
